[all]
webchat-server ansible_host=YOUR_SERVER_IP ansible_user=root

[databases]
webchat-server

[backend]
webchat-server

[frontend]
webchat-server

[all:vars]
ansible_python_interpreter=/usr/bin/python3
